GET http://localhost:3000/api/v2/tag
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInN1YiI6MSwiaWF0IjoxNTkxNjA2MjMwLCJleHAiOjE2MjMxNjM4MzB9.WoLAK1p2xCSmAUyqqd9NAuwrfT7quDsfM15pHWqxC_s

###

POST http://localhost:3000/api/v2/tag/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInN1YiI6MSwiaWF0IjoxNTkxNjA2MjMwLCJleHAiOjE2MjMxNjM4MzB9.WoLAK1p2xCSmAUyqqd9NAuwrfT7quDsfM15pHWqxC_s
content-type: application/json

{
  "name": "expressjs"
}

###

GET http://localhost:3000/api/v2/tag/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInN1YiI6MSwiaWF0IjoxNTkxNjA2MjMwLCJleHAiOjE2MjMxNjM4MzB9.WoLAK1p2xCSmAUyqqd9NAuwrfT7quDsfM15pHWqxC_s

###

PATCH http://localhost:3000/api/v2/tag/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInN1YiI6MSwiaWF0IjoxNTkxNjA2MjMwLCJleHAiOjE2MjMxNjM4MzB9.WoLAK1p2xCSmAUyqqd9NAuwrfT7quDsfM15pHWqxC_s
content-type: application/json

{
  "name": "expressjs"
}

###

DELETE http://localhost:3000/api/v2/tag/20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInN1YiI6MSwiaWF0IjoxNTkxNjA2MjMwLCJleHAiOjE2MjMxNjM4MzB9.WoLAK1p2xCSmAUyqqd9NAuwrfT7quDsfM15pHWqxC_s

###