GET http://localhost:3000/api/v2/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTI2NzE0ODQsImV4cCI6MTYyNDIyOTA4NH0.ohdQLD5yPagRs2z7Vsw34VgfUa4mwvC6ksgQK91qbcg

###

GET http://localhost:3000/api/v2/user/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTI2NzE0ODQsImV4cCI6MTYyNDIyOTA4NH0.ohdQLD5yPagRs2z7Vsw34VgfUa4mwvC6ksgQK91qbcg

###

POST http://localhost:3000/api/v2/user/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTI2NzE0ODQsImV4cCI6MTYyNDIyOTA4NH0.ohdQLD5yPagRs2z7Vsw34VgfUa4mwvC6ksgQK91qbcg
content-type: application/json

{
  "employeeCode": "1039",
  "employeeName": "Patiphat Prathumthong",
  "username": "Got",
  "password": "1010",
  "activated": true,
  "isAdmin": false
}

###

PATCH http://localhost:3000/api/v2/user/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTI2NzE0ODQsImV4cCI6MTYyNDIyOTA4NH0.ohdQLD5yPagRs2z7Vsw34VgfUa4mwvC6ksgQK91qbcg
content-type: application/json

{
  "employeeCode": "1039",
  "employeeName": "Patiphat Prathumthong",
  "username": "Got",
  "password": "1010",
  "activated": false,
  "isAdmin": false
}
