GET http://localhost:3000/api/v2/tag
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTI2NzE0ODQsImV4cCI6MTYyNDIyOTA4NH0.ohdQLD5yPagRs2z7Vsw34VgfUa4mwvC6ksgQK91qbcg

###

POST http://localhost:3000/api/v2/tag/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTI2NzE0ODQsImV4cCI6MTYyNDIyOTA4NH0.ohdQLD5yPagRs2z7Vsw34VgfUa4mwvC6ksgQK91qbcg
content-type: application/json

{
  "name": "expressjs"
}

###

GET http://localhost:3000/api/v2/tag/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTI2NzE0ODQsImV4cCI6MTYyNDIyOTA4NH0.ohdQLD5yPagRs2z7Vsw34VgfUa4mwvC6ksgQK91qbcg

###

PATCH http://localhost:3000/api/v2/tag/15
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTI2NzE0ODQsImV4cCI6MTYyNDIyOTA4NH0.ohdQLD5yPagRs2z7Vsw34VgfUa4mwvC6ksgQK91qbcg
content-type: application/json

{
  "name": "expressjs"
}

###

DELETE http://localhost:3000/api/v2/tag/20
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTI2NzE0ODQsImV4cCI6MTYyNDIyOTA4NH0.ohdQLD5yPagRs2z7Vsw34VgfUa4mwvC6ksgQK91qbcg
