POST http://localhost:3000/api/v2/auth/login
content-type: application/json

{
  "username": "1039",
  "password": "1010"
}

###

GET http://localhost:3000/api/v2/auth/sso

###

GET http://localhost:3000/api/v2/auth/me
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTYwMzM0NjAsImV4cCI6MTYyNzU5MTA2MH0.RgIojo6kTpUXmG1KZjpJg6TBxMBsqnVs0E7JyLV5WE0

###

GET http://localhost:3000/api/v2/auth/refreshToken
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTYwMzM0NjAsImV4cCI6MTYyNzU5MTA2MH0.RgIojo6kTpUXmG1KZjpJg6TBxMBsqnVs0E7JyLV5WE0
