GET http://localhost:3000/api/v2/icon
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q

###

GET http://localhost:3000/api/v2/icon/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q

###

DELETE http://localhost:3000/api/v2/icon/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q
content-type: application/json

{
  "image": "e9c4f95221e9b9de84c95a81bbde6f78"
}
