GET http://localhost:3000/api/v2/icon
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTYwMzM0NjAsImV4cCI6MTYyNzU5MTA2MH0.RgIojo6kTpUXmG1KZjpJg6TBxMBsqnVs0E7JyLV5WE0

###

GET http://localhost:3000/api/v2/icon/5
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTYwMzM0NjAsImV4cCI6MTYyNzU5MTA2MH0.RgIojo6kTpUXmG1KZjpJg6TBxMBsqnVs0E7JyLV5WE0

###

DELETE http://localhost:3000/api/v2/icon/19
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTYwMzM0NjAsImV4cCI6MTYyNzU5MTA2MH0.RgIojo6kTpUXmG1KZjpJg6TBxMBsqnVs0E7JyLV5WE0
content-type: application/json

{
  "image": "e9c4f95221e9b9de84c95a81bbde6f78"
}
