GET http://localhost:3000/api/v2/url
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q
content-type: application/json

{
  "enabled": true,
  "expiry": true,
  "createdBy": null,
  "createdAt": ["2019-12-01", "2020-06-20"],
  "tags": [9, 13]
}

###

POST http://localhost:3000/api/v2/url/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q
content-type: application/json

{
  "href": "http://expressjs.com/",
  "title": "",
  "expiry": "",
  "redirect": "",
  "tags": [9, 10]
}

###

GET http://localhost:3000/api/v2/url/33365
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q

###

PATCH http://localhost:3000/api/v2/url/33379
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q
content-type: application/json

{
  "key": "expr3s",
  "href": "http://expressjs.com/en",
  "title": "expressjs",
  "expiry": "",
  "redirect": "",
  "tags": [13, 17]
}

###

DELETE http://localhost:3000/api/v2/url/33379
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q

###

GET http://localhost:3000/api/v2/url/statistics
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q
