GET http://localhost:3000/api/v2/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q

###

GET http://localhost:3000/api/v2/user/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q

###

POST http://localhost:3000/api/v2/user/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q
content-type: application/json

{
  "employeeCode": "1040",
  "employeeName": "Patiphat Prathumthong",
  "username": "member2",
  "password": "1010",
  "activated": true,
  "isAdmin": false
}

###

PATCH http://localhost:3000/api/v2/user/12
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJ1bnNldCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTU0MDA5MTEsImV4cCI6MTYyNjk1ODUxMX0.KyAKU4lRvnLpFefAejSyd0dA21DTTGwu8qUcoMCp11Q
content-type: application/json

{
  "employeeCode": "1040",
  "employeeName": "Patiphat Prathumthong",
  "username": "member",
  "password": "1010",
  "activated": false,
  "isAdmin": false
}
