GET http://localhost:3000/api/v2/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTYwMzM0NjAsImV4cCI6MTYyNzU5MTA2MH0.RgIojo6kTpUXmG1KZjpJg6TBxMBsqnVs0E7JyLV5WE0

###

GET http://localhost:3000/api/v2/user/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTYwMzM0NjAsImV4cCI6MTYyNzU5MTA2MH0.RgIojo6kTpUXmG1KZjpJg6TBxMBsqnVs0E7JyLV5WE0

###

POST http://localhost:3000/api/v2/user/create
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTYwMzM0NjAsImV4cCI6MTYyNzU5MTA2MH0.RgIojo6kTpUXmG1KZjpJg6TBxMBsqnVs0E7JyLV5WE0
content-type: application/json

{
  "employeeCode": "1039",
  "employeeName": "Patiphat Prathumthong",
  "username": "Got",
  "password": "1010",
  "activated": true,
  "isAdmin": false
}

###

PATCH http://localhost:3000/api/v2/user/3
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJwcm9qZWN0X2JzbCIsInVpZCI6Mywic3ViIjoxMDM5LCJpYXQiOjE1OTYwMzM0NjAsImV4cCI6MTYyNzU5MTA2MH0.RgIojo6kTpUXmG1KZjpJg6TBxMBsqnVs0E7JyLV5WE0
content-type: application/json

{
  "employeeCode": "1039",
  "employeeName": "Patiphat Prathumthong",
  "username": "Got",
  "password": "1010",
  "activated": false,
  "isAdmin": false
}
